### ISSUE TITLE
Type mismatch 

### ISSUE THREAD

**Issue by romaluca** [kineapps/flutter_image_utilities#1]
Hi when i try to launch my app with your plugin this error raise:

`/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_image_utilities-1.0.0/android/src/main/kotlin/com/kineapps/flutter_image_utilities/FlutterImageUtilitiesPlugin.kt: (135, 58): Type mismatch: inferred type is String? but String was expected`

How can i do?

Thanks

**Comment by kinex** [comment]
Hi. Is there same problem with the version 2.0 (just published)?

**Comment by romaluca** [comment]
Hi, in the 2.0 version the same error is in row 133
flutter/.pub-cache/hosted/pub.dartlang.org/flutter_image_utilities-2.0.0/android/src/main/kotlin/com/kineapps/flutter_image_utilities/FlutterImageUtilitiesPlugin.kt: (133, 58): Type mismatch: inferred type is String? but String was expected

**Comment by romaluca** [comment]
I was using kotlin 1.4. with 1.3 works well 
Thanks

**Comment by kinex** [comment]
2.01 should fix it. Please test again.

**Comment by romaluca** [comment]
it works! thanks
